### ISSUE TITLE
Error building this project

### ISSUE THREAD

**Issue by RujjhidHD** [creativetrendsapps/SimplicityBrowser#2]
I had this error: http://i.imgur.com/BUxURzz.jpg

**Comment by creativetrendsapps** [comment]
@RujjhidHD have you tried rebuilding the project? If so, I'll reupload the full project later today.

**Comment by RujjhidHD** [comment]
Error:A problem occurred configuring project ':app'.
> Cannot evaluate module saxrssreader : Configuration with name 'default' not found.

**Comment by creativetrendsapps** [comment]
@RujjhidHD sorry, you need to download this project and import it as a module: https://github.com/matshofman/Android-RSS-Reader-Library. Clean the project and it should build fine. Let me know if this corrects the issue.

**Comment by RujjhidHD** [comment]
@creativetrendsapps You are the best, it worked 👍
But, i had this error when i tried to build: http://i.imgur.com/SxbuuSU.png

**Comment by RujjhidHD** [comment]
@creativetrendsapps Yeah, you are the best, it worked 👍 
But when i tried to build the apk i had this error: http://i.imgur.com/QpxKDgj.png

**Comment by creativetrendsapps** [comment]
@RujjhidHD you can remove (delete) both of those classes. They aren't needed.

**Comment by RujjhidHD** [comment]
@creativetrendsapps Thank you, it worked :)

**Comment by creativetrendsapps** [comment]
@RujjhidHD you're welcome.
